spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_board?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: dkagh1.

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect  # JPA ?????? ??? (InnoDB)
    open-in-view: false
    show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: update  # none, update, create, create-drop, validate

  mvc:
    hiddenmethod:
      filter:
        enabled: true # GET, POST ? ? ??? PUT, DELETE ?? ???? ???? ?? ??

  devtools:
    livereload:
      enabled: true

  logging:
    level:
      org:
        hibernate:
          SQL: DEBUG
          type:
            descriptor:
              sql:
                BasicBinder: TRACE
